#pragma once

#include <cstdint>
#include <vector>

#include "baguette/core/LinearExpr.hpp"
#include "baguette/lp/LPResult.hpp"
#include "baguette/model/Model.hpp"

namespace baguette {

/// A linear cut expressed in original model-variable space: expr ≥ rhs.
///
/// Generated by generateGMICuts() from fractional tableau rows; consumed by
/// the B&C loop in solveMILP() via Model::addLPConstraint().
/// The sense is always GreaterEq.
struct Cut {
    LinearExpr expr;
    double     rhs = 0.0;
};

/// Generate Gomory Mixed-Integer (GMI) cuts from fractional tableau rows.
///
/// Each row in @p rows corresponds to a basic fractional integer variable.
/// The GMI formula is applied and the resulting cut is expressed in terms of
/// original model variables by substituting slacks, surpluses, and upper-bound
/// slacks back using current model bounds and constraint data.
///
/// @param rows        Fractional rows from LPDetailedResult::fractionalRows.
/// @param basis       BasisRecord from the same solve (colKind / colOrigin metadata).
/// @param model       The current B&B-node model (variable bounds and constraints).
/// @param maxCuts     Maximum number of cuts to return. 0 = return all.
/// @param intFeasTol  Integer feasibility tolerance (same as BBOptions::intFeasTol).
///                    Used for near-zero GMI coefficient filtering, consistent with
///                    the MILP branching tolerance.
/// @returns           At most @p maxCuts cuts, in the order they were generated.
///
/// @note Complexity: O(|rows| × n × nnz_avg) where n = number of SF columns and
///   nnz_avg = average non-zeros per model constraint. Dominated by slack substitution.
std::vector<Cut> generateGMICuts(const std::vector<FractionalRow>& rows,
                                  const BasisRecord&                basis,
                                  const Model&                      model,
                                  uint32_t                          maxCuts     = 0,
                                  double                            intFeasTol  = 1e-6);

} // namespace baguette
