#pragma once

#include <cstdint>
#include <vector>

#include "baguette/core/LinearExpr.hpp"
#include "baguette/lp/LPResult.hpp"
#include "baguette/model/Model.hpp"

namespace baguette {

/// A linear cut expressed in original model-variable space: expr ≥ rhs.
///
/// Generated by generateGMICuts() from fractional tableau rows; consumed by
/// the B&C loop in solveMILP() via Model::addConstraint().
/// The sense is always GreaterEq.
struct Cut {
    LinearExpr expr;
    double     rhs = 0.0;
};

/// Per-variable pseudo-cost accumulators for branching score estimation.
///
/// Pseudo-costs estimate the objective change per unit of fractionality when
/// branching up (lb raised to ceil) or down (ub lowered to floor).
/// Initialised to zero and updated at each node where the LP is solved.
///
/// size of each vector == Model::numVars() at construction time.
struct PseudoCosts {
    std::vector<double>   upCost;    ///< Accumulated up-branch objective deltas.
    std::vector<uint32_t> upCount;   ///< Number of up-branch observations.
    std::vector<double>   downCost;  ///< Accumulated down-branch objective deltas.
    std::vector<uint32_t> downCount; ///< Number of down-branch observations.
};

/// Generate Gomory Mixed-Integer (GMI) cuts from fractional tableau rows.
///
/// Each row in @p rows corresponds to a basic fractional integer variable.
/// The GMI formula is applied and the resulting cut is expressed in terms of
/// original model variables by substituting slacks, surpluses, and upper-bound
/// slacks back using current model bounds and constraint data.
///
/// @param rows        Fractional rows from LPDetailedResult::fractionalRows.
/// @param basis       BasisRecord from the same solve (colKind / colOrigin metadata).
/// @param model       The current B&B-node model (variable bounds and constraints).
/// @param maxCuts     Maximum number of cuts to return. 0 = return all.
/// @param intFeasTol  Integer feasibility tolerance (same as BBOptions::intFeasTol).
///                    Used for near-zero GMI coefficient filtering, consistent with
///                    the MILP branching tolerance.
/// @returns           At most @p maxCuts cuts, in the order they were generated.
///
/// @note Complexity: O(|rows| × n × nnz_avg) where n = number of SF columns and
///   nnz_avg = average non-zeros per model constraint. Dominated by slack substitution.
std::vector<Cut> generateGMICuts(const std::vector<FractionalRow>& rows,
                                  const BasisRecord&                basis,
                                  const Model&                      model,
                                  uint32_t                          maxCuts     = 0,
                                  double                            intFeasTol  = 1e-6);

/// Initialise a PseudoCosts object for a model with @p numVars variables.
/// All accumulators are set to zero.
PseudoCosts initPseudoCosts(uint32_t numVars);

/// Select the variable to branch on using pseudo-cost product scoring.
///
/// For each fractional integer variable i, the estimated degradations are:
///   d_up[i]   = (upCount[i]   > 0) ? upCost[i]/upCount[i]   * (1 − frac[i])
///                                   : frac_score fallback
///   d_down[i] = (downCount[i] > 0) ? downCost[i]/downCount[i] * frac[i]
///                                   : frac_score fallback
/// score[i] = max(d_up[i], eps) × max(d_down[i], eps)
/// where frac_score = min(frac, 1−frac) (MostFractional fallback).
///
/// @returns Variable id to branch on, or -1 if all integer variables are
///          within @p intFeasTol of an integer value.
/// @note Complexity: O(|intVarIds|).
int selectBranchVarPseudoCost(const std::vector<double>&   sol,
                               const std::vector<uint32_t>& intVarIds,
                               const PseudoCosts&           pc,
                               double                       intFeasTol);

/// Update pseudo-costs after observing a branching outcome at one child node.
///
/// @param pc          The pseudo-cost table to update (in/out).
/// @param varId       Model variable id that was branched on.
/// @param frac        Fractional part of varId's value at the time of branching.
/// @param parentObj   LP objective at the branching node.
/// @param childObj    LP objective at the child node after re-solving.
/// @param branchedUp  True if the child is the up branch (lb raised to ceil).
/// @note Complexity: O(1).
void updatePseudoCosts(PseudoCosts& pc,
                       uint32_t    varId,
                       double      frac,
                       double      parentObj,
                       double      childObj,
                       bool        branchedUp);

} // namespace baguette
